library:
  visible: false
source:
  visible: true
  percentage: 0.6253846153846154
board:
  visible_edition: true
  collapse_toolbox: false
  user_permissions:
    can_change_initial_board: false
    can_change_initial_board_source: false
    can_edit_board: false
    can_view_size_section: false
    can_view_attire_section: true
  active: 1
  initial_board_source: selected
execution_speed:
  user_permissions:
    can_change_speed: false
  active: high
attire:
  visible: true
  user_permissions:
    can_toggle_visibility: true
  active: Sembrando tomates
initialDescription: true
blocks:
  visible:
    - ProcedimientosPrimitivos
  disabled: []
customErrors: null
name: 'El docente, el granjero y las bolitas'
activity:
  construction_mode: blocks
  execution_type: sequential
