name: Morse
rules:
  - when:
      red: 0
      green: 0
      blue: '*'
      black: 0
    image: null
    text: ' '
  - when:
      red: 1
      green: 0
      blue: 0
      black: 0
    image: punto.png
    text: null
  - when:
      red: 2
      green: 0
      blue: 0
      black: 0
    image: raya.png
    text: null
  - when:
      red: 0
      green: 0
      blue: 0
      black: 1
    image: null
    text: A
  - when:
      red: 0
      green: 0
      blue: 0
      black: 2
    image: null
    text: B
  - when:
      red: 0
      green: 0
      blue: 0
      black: 3
    image: null
    text: C
  - when:
      red: 0
      green: 0
      blue: 0
      black: 4
    image: null
    text: D
  - when:
      red: 0
      green: 0
      blue: 0
      black: 5
    image: null
    text: E
  - when:
      red: 0
      green: 0
      blue: 0
      black: 6
    image: null
    text: F
  - when:
      red: 0
      green: 0
      blue: 0
      black: 7
    image: null
    text: G
  - when:
      red: 0
      green: 0
      blue: 0
      black: 8
    image: null
    text: H
  - when:
      red: 0
      green: 0
      blue: 0
      black: 9
    image: null
    text: I
  - when:
      red: 0
      green: 0
      blue: 0
      black: 10
    image: null
    text: J
  - when:
      red: 0
      green: 0
      blue: 0
      black: 11
    image: null
    text: K
  - when:
      red: 0
      green: 0
      blue: 0
      black: 12
    image: null
    text: L
  - when:
      red: 0
      green: 0
      blue: 0
      black: 13
    image: null
    text: M
  - when:
      red: 0
      green: 0
      blue: 0
      black: 14
    image: null
    text: 'N'
  - when:
      red: 0
      green: 0
      blue: 0
      black: 15
    image: null
    text: O
  - when:
      red: 0
      green: 0
      blue: 0
      black: 16
    image: null
    text: P
  - when:
      red: 0
      green: 0
      blue: 0
      black: 17
    image: null
    text: Q
  - when:
      red: 0
      green: 0
      blue: 0
      black: 18
    image: null
    text: R
  - when:
      red: 0
      green: 0
      blue: 0
      black: 19
    image: null
    text: S
  - when:
      red: 0
      green: 0
      blue: 0
      black: 20
    image: null
    text: T
  - when:
      red: 0
      green: 0
      blue: 0
      black: 21
    image: null
    text: U
  - when:
      red: 0
      green: 0
      blue: 0
      black: 22
    image: null
    text: V
  - when:
      red: 0
      green: 0
      blue: 0
      black: 23
    image: null
    text: W
  - when:
      red: 0
      green: 0
      blue: 0
      black: 24
    image: null
    text: X
  - when:
      red: 0
      green: 0
      blue: 0
      black: 25
    image: null
    text: 'Y'
  - when:
      red: 0
      green: 0
      blue: 0
      black: 26
    image: null
    text: Z
