name: Rayuela
rules:
  - when:
      red: 0
      green: '*'
      blue: '*'
      black: 1
    image: r1.png
    text: null
  - when:
      red: 1
      green: '*'
      blue: '*'
      black: 1
    image: r1p.png
    text: null
  - when:
      red: 0
      green: '*'
      blue: '*'
      black: 2
    image: r2.png
    text: null
  - when:
      red: 1
      green: '*'
      blue: '*'
      black: 2
    image: r2p.png
    text: null
  - when:
      red: 0
      green: '*'
      blue: '*'
      black: 3
    image: r3.png
    text: null
  - when:
      red: 1
      green: '*'
      blue: '*'
      black: 3
    image: r3p.png
    text: null
  - when:
      red: 0
      green: '*'
      blue: '*'
      black: 4
    image: r4.png
    text: null
  - when:
      red: 1
      green: '*'
      blue: '*'
      black: 4
    image: r4p.png
    text: null
  - when:
      red: 0
      green: '*'
      blue: '*'
      black: 5
    image: r5.png
    text: null
  - when:
      red: 1
      green: '*'
      blue: '*'
      black: 5
    image: r5p.png
    text: null
  - when:
      red: 0
      green: '*'
      blue: '*'
      black: 6
    image: r6.png
    text: null
  - when:
      red: 1
      green: '*'
      blue: '*'
      black: 6
    image: r6p.png
    text: null
  - when:
      red: 0
      green: '*'
      blue: '*'
      black: 7
    image: r7.png
    text: null
  - when:
      red: 1
      green: '*'
      blue: '*'
      black: 7
    image: r7p.png
    text: null
  - when:
      red: 0
      green: '*'
      blue: '*'
      black: 8
    image: r8.png
    text: null
  - when:
      red: 1
      green: '*'
      blue: '*'
      black: 8
    image: r8p.png
    text: null
  - when:
      red: 0
      green: '*'
      blue: '*'
      black: 0
    image: p0.png
    text: null
  - when:
      red: 1
      green: '*'
      blue: '*'
      black: 0
    image: p1.png
    text: null
  - when:
      red: 2
      green: '*'
      blue: '*'
      black: 0
    image: p2.png
    text: null
  - when:
      red: 3
      green: '*'
      blue: '*'
      black: 0
    image: p3.png
    text: null
  - when:
      red: 4
      green: '*'
      blue: '*'
      black: 0
    image: p4.png
    text: null
  - when:
      red: 5
      green: '*'
      blue: '*'
      black: 0
    image: p5.png
    text: null
  - when:
      red: 6
      green: '*'
      blue: '*'
      black: 0
    image: p6.png
    text: null
  - when:
      red: 7
      green: '*'
      blue: '*'
      black: 0
    image: p7.png
    text: null
  - when:
      red: 8
      green: '*'
      blue: '*'
      black: 0
    image: p8.png
    text: null
